NSE_SECTORS = {
    # Leading & Broad
    "BANKNIFTY": "^NSEBANK",
    "AUTO": "^CNXAUTO",
    "REALTY": "^CNXREALTY",
    "CONSR DURBL": "^CNXCONSUM",
    "CONSUMPTION": "^CNXCONSUMP",
    "SERVICES": "^CNXSERVICE",
    
    # Improving
    "IT": "^CNXIT",
    "SENSEX": "^BSESN",
    
    # Weakening
    "FINNIFTY": "NIFTY_FIN_SERVICE.NS",
    "PVT BANK": "NIFTY_PVT_BANK.NS",
    "PHARMA": "^CNXPHARMA",
    "HEALTHCARE": "^CNXHEALTH",
    "ENERGY": "^CNXENERGY",
    "INFRA": "^CNXINFRA",
    "METAL": "^CNXMETAL",
    "MEDIA": "^CNXMEDIA",
    "MIDCAP": "^NSEMDCP50",
    "DEFENCE": "NIFTY_DEFENCE.NS",
    "CHEMICALS": "NIFTY_CHEMICALS.NS",
    "CAPITAL MRKT": "NIFTY_CAP_MRKT.NS",
    
    # Lagging
    "FMCG": "^CNXFMCG",
    "PSU BANK": "^CNXPSUBANK",
    "OIL & GAS": "^CNXOILGAS",
    "COMMODITIES": "^CNXCOMMODITIES"
}
